# Generated by Django 4.1.3 on 2022-11-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'январь'), ('2', 'февраль'), ('3', 'март'), ('4', 'апрель'), ('5', 'май'), ('6', 'июнь'), ('7', 'июль'), ('8', 'август'), ('9', 'сентябрь'), ('10', 'октябрь'), ('11', 'ноябрь'), ('12', 'декабрь')], default='1', max_length=32)),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_security', models.CharField(default='Дежурный по кабинетам', max_length=128)),
            ],
            options={
                'verbose_name': 'Тип дежурств',
                'verbose_name_plural': 'Тип дежурства',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_people', models.CharField(default='Дмитриев', max_length=128)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='table.month')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.workers')),
                ('type_security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.securitytype')),
            ],
            options={
                'verbose_name': 'Дежурств',
                'verbose_name_plural': 'Дежурства',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15, verbose_name='Автор комментария')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.month')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
