# Generated by Django 4.1.3 on 2022-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
