# Generated by Django 4.1.3 on 2022-11-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_month_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='table.workers'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('1', 'январь'), ('2', 'февраль'), ('3', 'март'), ('4', 'апрель'), ('5', 'май'), ('6', 'июнь'), ('7', 'июль'), ('8', 'август'), ('9', 'сентябрь'), ('10', 'октябрь'), ('11', 'ноябрь'), ('12', 'декабрь')], max_length=32),
        ),
    ]
